SkappHQ/skapp-be

- src/main/java/com/rootcode/skapp/leaveplanner/payload/CustomEntitlementsFilterDto.java
- src/main/java/com/rootcode/skapp/leaveplanner/repository/LeaveEntitlementRepository.java
- src/main/java/com/rootcode/skapp/leaveplanner/repository/impl/LeaveEntitlementRepositoryImpl.java
- src/main/java/com/rootcode/skapp/leaveplanner/service/impl/LeaveEntitlementServiceImpl.java
> fix(leave planner): fixed custom allocation filters are not working

- src/main/java/com/skapp/community/common/component/ExceptionLoggingFilter.java
- src/main/java/com/skapp/community/common/component/JwtAuthFilter.java
- src/main/java/com/skapp/community/common/constant/CommonMessageConstant.java
- src/main/java/com/skapp/community/common/exception/GlobalExceptionHandler.java
- src/main/java/com/skapp/community/common/service/AuthService.java
- src/main/java/com/skapp/community/common/service/JwtService.java
- src/main/java/com/skapp/community/common/service/impl/AuthServiceImpl.java
- src/main/java/com/skapp/community/common/service/impl/JwtServiceImpl.java
- src/main/java/com/skapp/community/common/type/EmailBodyTemplates.java
- src/main/java/com/skapp/community/peopleplanner/payload/email/PeopleEmailDynamicFields.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
- src/main/resources/community/messages/common-messages.properties
- In this flow I created super admin creation apis
- Verify otp apis
- resend otp apis
- organization creation and route53 creation
1.
> feat: #7 ep signup and org creation flow

- pom.xml
- src/main/java/com/skapp/community/common/model/User.java
- src/main/java/com/skapp/community/common/service/JwtService.java
- src/main/java/com/skapp/community/common/service/impl/JwtServiceImpl.java
> sso login with google implementation

- src/main/java/com/skapp/SkappApplication.java
- src/main/java/com/skapp/community/common/component/AsyncConfiguration.java
- src/main/java/com/skapp/community/common/component/AsyncEmailSender.java
- src/main/java/com/skapp/community/common/component/ExceptionLoggingFilter.java
- src/main/java/com/skapp/community/common/controller/v1/RobotsController.java
- src/main/java/com/skapp/community/common/exception/GlobalExceptionHandler.java
- src/main/java/com/skapp/community/common/model/User.java
- src/main/java/com/skapp/community/common/service/JwtService.java
- src/main/java/com/skapp/community/common/service/impl/EmailServiceImpl.java
- src/main/java/com/skapp/community/common/service/impl/JwtServiceImpl.java
- src/main/java/com/skapp/community/common/service/impl/NotificationServiceImpl.java
- src/main/java/com/skapp/community/common/type/LoginMethod.java
- src/main/java/com/skapp/community/common/util/LoginMethod.java
- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveAnalyticsServiceImpl.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/JobServiceImpl.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/TeamServiceImpl.java
- src/main/java/com/skapp/community/timeplanner/service/impl/TimeServiceImpl.java
- src/main/resources/community/db/changelog/db.changelog.yml
- src/main/resources/community/db/changelog/ddl-script/common-ddl-script-v1-edit-user.sql
- src/test/resources/data.sql
> feat: signin signup flow for google sso

- src/main/java/com/skapp/community/common/controller/v1/HealthController.java
> updated health payload

- pom.xml
- src/main/java/com/skapp/community/common/component/AsyncEmailSender.java
- src/main/java/com/skapp/community/common/component/impl/AsyncEmailSenderImpl.java
- src/main/java/com/skapp/community/common/service/impl/EmailServiceImpl.java
- src/main/java/com/skapp/community/common/type/EmailBodyTemplates.java
- src/main/resources/community/templates/email/email-templates.yml
> feat(email): sendgrid implementation

- src/main/java/com/skapp/community/common/component/ProfileActivator.java
- src/main/java/com/skapp/community/common/constant/CommonConstants.java
- src/main/java/com/skapp/community/peopleplanner/constant/PeopleMessageConstant.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
- src/main/resources/community/messages/people-messages.properties
> feat: bulk upload limitation for ep

- pom.xml
- src/main/java/com/skapp/community/common/service/impl/EmailServiceImpl.java
- src/main/resources/community/templates/email/en/common/common-module-credential-based-creation-tenant-url.html
- src/main/resources/community/templates/email/en/common/common-module-email-verify.html
- src/main/resources/community/templates/email/en/common/common-module-sso-creation-tenant-url.html
> fix(email): fixed otp not shared via email

- src/main/java/com/skapp/community/peopleplanner/repository/EmployeeManagerDao.java
- src/main/java/com/skapp/community/peopleplanner/repository/EmployeeManagerRepository.java
- src/main/java/com/skapp/community/peopleplanner/repository/TeamDao.java
- src/main/java/com/skapp/community/peopleplanner/repository/impl/EmployeeManagerRepositoryImpl.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
- src/main/java/com/skapp/community/timeplanner/repository/TimeRecordRepository.java
- src/main/java/com/skapp/community/timeplanner/repository/TimeRecordRepositoryImpl.java
- src/main/java/com/skapp/community/timeplanner/service/impl/TimeServiceImpl.java
> Attendance summary fix

- src/main/java/com/skapp/community/leaveplanner/model/LeaveRequestEntitlement.java
> fix: leave apply flow issues

- src/main/java/com/skapp/community/common/controller/v1/HealthController.java
- src/main/java/com/skapp/community/common/payload/response/HealthResponse.java
- src/main/resources/application.yml
> fix: health version

- src/main/java/com/skapp/community/peopleplanner/model/JobFamilyTitle.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
> fixed employee adding error

- src/main/java/com/skapp/community/peopleplanner/repository/impl/EmployeeTeamRepositoryImpl.java
> Fix: dashboard summary

- src/main/java/com/skapp/community/common/service/BulkContextService.java
- src/main/java/com/skapp/community/common/service/impl/BulkContextServiceImpl.java
- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveEntitlementServiceImpl.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
- src/test/resources/application.yml
> Leave bulk upload not working

- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveServiceImpl.java
- src/main/java/com/skapp/community/peopleplanner/repository/impl/EmployeeTeamRepositoryImpl.java
- src/main/resources/community/db/changelog/db.changelog.yml
- src/test/java/com/skapp/community/peopleplanner/controller/v1/PeopleControllerIntegrationTest.java
> Feat: tenant availability and sso signin authPic

- src/main/java/com/skapp/community/leaveplanner/repository/impl/LeaveRequestRepositoryImpl.java
- src/test/java/com/skapp/community/peopleplanner/controller/v1/PeopleControllerIntegrationTest.java
> fix(Leave): leave request not fetched

- src/main/java/com/skapp/community/leaveplanner/controller/v1/LeaveTypeController.java
- src/test/java/com/skapp/community/peopleplanner/controller/v1/PeopleControllerIntegrationTest.java
> fix(leave): leave manager does not have permission to get teams

- src/main/java/com/skapp/community/leaveplanner/payload/CustomEntitlementsFilterDto.java
- src/main/java/com/skapp/community/leaveplanner/repository/LeaveEntitlementRepository.java
- src/main/java/com/skapp/community/leaveplanner/repository/impl/LeaveEntitlementRepositoryImpl.java
- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveEntitlementServiceImpl.java
> fix(leave): custom leave allocation filters not working

- src/main/java/com/skapp/community/peopleplanner/payload/response/PeopleDashboardSummaryResponseDto.java
- src/main/java/com/skapp/community/peopleplanner/repository/EmployeeRepository.java
- src/main/java/com/skapp/community/peopleplanner/repository/impl/EmployeeRepositoryImpl.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleAnalyticsServiceImpl.java
- src/test/java/com/skapp/community/peopleplanner/controller/v1/PeopleControllerIntegrationTest.java
> fixing incorrect people count showing

- src/main/java/com/skapp/community/common/util/Validation.java
- src/test/resources/data.sql
> fix - password special char validations

- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveTypeServiceImpl.java
> fix - #120 - remove emoji validation from leave type

- src/main/java/com/skapp/community/leaveplanner/controller/v1/LeaveEntitlementController.java
> fix(people): leave entitlement bulk upload 403 error

- src/main/java/com/skapp/community/peopleplanner/repository/impl/EmployeeRepositoryImpl.java
> Fix(leave): Leave Entitlement Bulk Upload Issues

- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveEntitlementServiceImpl.java
> fix(leave bulk): leave bulk not submit empty

- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveTypeServiceImpl.java
> fix(leave): leave type deactivation error

- src/main/java/com/skapp/community/common/constant/CommonMessageConstant.java
- src/main/resources/community/messages/common-messages.properties
> fix: jwt auth filter changes

- src/main/java/com/skapp/community/leaveplanner/payload/response/EmployeeLeaveEntitlementReportExportDto.java
- src/main/java/com/skapp/community/leaveplanner/payload/response/EmployeeLeaveRequestReportExportDto.java
- src/main/java/com/skapp/community/leaveplanner/repository/impl/LeaveEntitlementRepositoryImpl.java
- src/main/java/com/skapp/community/leaveplanner/repository/impl/LeaveRequestRepositoryImpl.java
> fix: #181 leave report file api failing issue

- src/main/java/com/skapp/community/common/util/Validation.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
- src/main/java/com/skapp/community/peopleplanner/util/Validations.java
> fix(people): add space capability for all name add and update

- src/main/java/com/skapp/community/peopleplanner/constant/PeopleMessageConstant.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
- src/main/resources/community/messages/people-messages.properties
> fix(people): user termination flow no as intended

- .gitmodules
> feat: submodule changes

- src/main/java/com/skapp/community/peopleplanner/repository/impl/EmployeeRepositoryImpl.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
> feat: impl changes in supervisor permission api

- src/main/java/com/skapp/community/peopleplanner/controller/v1/HolidayController.java
> fix(holiday): holidays are not shown for employee fixed

- src/main/java/com/skapp/community/peopleplanner/repository/EmployeeManagerDao.java
- src/main/java/com/skapp/community/peopleplanner/repository/EmployeeTeamDao.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
> fix : search changes employee team

- src/main/java/com/skapp/community/leaveplanner/repository/impl/LeaveRequestRepositoryImpl.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/RolesServiceImpl.java
> fix(leave): invalid leave dashboard pending leave request count

- src/main/java/com/skapp/community/peopleplanner/payload/request/EmployeeUpdateDto.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
> fix: add validation to update user

- src/main/java/com/skapp/community/common/component/JwtAuthFilter.java
- src/main/java/com/skapp/community/common/config/SecurityConfig.java
- src/main/java/com/skapp/community/common/model/User.java
- src/main/java/com/skapp/community/common/security/AuthorityService.java
- src/main/java/com/skapp/community/common/security/AuthorityServiceImpl.java
- src/main/java/com/skapp/community/common/security/SkappUserDetails.java
- src/main/java/com/skapp/community/common/security/UserDetailsServiceImpl.java
- src/main/java/com/skapp/community/common/service/UserService.java
- src/main/java/com/skapp/community/common/service/impl/AuthServiceImpl.java
- src/main/java/com/skapp/community/common/service/impl/UserServiceImpl.java
- src/main/java/com/skapp/community/peopleplanner/repository/EmployeeTeamDao.java
- src/main/java/com/skapp/community/peopleplanner/service/RolesService.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/RolesServiceImpl.java
- src/test/java/com/skapp/community/common/controller/v1/OrganizationControllerIntegrationTest.java
- src/test/java/com/skapp/community/leaveplanner/controller/v1/LeaveAnalyticsControllerIntegrationTest.java
- src/test/java/com/skapp/community/leaveplanner/controller/v1/LeaveControllerIntegrationTest.java
- src/test/java/com/skapp/community/peopleplanner/controller/v1/HolidayControllerIntegrationTest.java
- src/test/java/com/skapp/community/peopleplanner/controller/v1/JobControllerIntegrationTest.java
- src/test/java/com/skapp/community/peopleplanner/controller/v1/PeopleControllerIntegrationTest.java
- src/test/java/com/skapp/community/timeplanner/controller/v1/TimeControllerIntegrationTest.java
> feat: enterprise abstraction spring security and roles

- src/main/java/com/skapp/community/common/service/impl/NotificationServiceImpl.java
> hotfix: firebase notification file

- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveAnalyticsServiceImpl.java
> fix: leave manager role show leave analytics

- src/main/java/com/skapp/community/common/service/AuthService.java
- src/main/java/com/skapp/community/common/service/impl/AuthServiceImpl.java
- src/main/java/com/skapp/community/peopleplanner/service/RolesService.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/RolesServiceImpl.java
> feat: move role related methods to role service

- src/main/java/com/skapp/community/common/constant/CommonMessageConstant.java
- src/main/java/com/skapp/community/common/controller/v1/AuthController.java
- src/main/java/com/skapp/community/common/payload/ReInvitationSkippedCountDto.java
- src/main/java/com/skapp/community/common/payload/request/ReInvitationRequestDto.java
- src/main/java/com/skapp/community/common/service/AuthService.java
- src/main/java/com/skapp/community/common/service/impl/AuthServiceImpl.java
- src/main/java/com/skapp/community/common/util/Validation.java
- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveEntitlementServiceImpl.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
- src/main/resources/community/messages/common-messages.properties
> feat: re invitation email sending user update

- src/main/java/com/skapp/community/timeplanner/service/impl/AttendanceNotificationServiceImpl.java
> fix: send both time request notification to employee

- pom.xml
- src/main/java/com/skapp/community/common/service/impl/AuthServiceImpl.java
- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveAnalyticsServiceImpl.java
- src/main/java/com/skapp/community/peopleplanner/repository/impl/EmployeeRepositoryImpl.java
> Fix: leave manager entitlements

- src/main/java/com/skapp/community/common/payload/request/UpdateOrganizationRequestDto.java
> fix: #172 - remove mandatory validation on organization website

- src/main/java/com/skapp/community/common/service/impl/FileStorageServiceImpl.java
- src/main/java/com/skapp/community/peopleplanner/model/JobFamilyTitle.java
- src/main/java/com/skapp/community/peopleplanner/service/RolesService.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/RolesServiceImpl.java
- src/main/java/com/skapp/community/timeplanner/controller/v1/TimeController.java
> fix: #169 - Toggle buttons in the Settings page are not in the enabled state by default

- src/main/java/com/skapp/community/timeplanner/controller/v1/TimeController.java
- src/main/java/com/skapp/community/timeplanner/payload/response/PendingTimeRequestsCountDto.java
- src/main/java/com/skapp/community/timeplanner/repository/TimeRequestRepository.java
- src/main/java/com/skapp/community/timeplanner/repository/TimeRequestRepositoryImpl.java
- src/main/java/com/skapp/community/timeplanner/service/TimeService.java
- src/main/java/com/skapp/community/timeplanner/service/impl/TimeServiceImpl.java
> feat: pending time request count api

- src/main/java/com/skapp/community/common/service/impl/JwtServiceImpl.java
> Hotfix: refresh token issue

- src/main/java/com/skapp/community/common/service/impl/JwtServiceImpl.java
* hotfix: refresh token issue
* fix: dynamic refresh token selection issue
* fix: formatting issue
* fix: formatting issue
- 
1.
> Hotfix: refresh token issue (#127)

- src/main/java/com/skapp/community/common/service/impl/JwtServiceImpl.java
* hotfix: refresh token issue
* fix: dynamic refresh token selection issue
* fix: formatting issue
* fix: formatting issue
- 
1.
> Hotfix: refresh token issue (#127) (#128)

- src/main/java/com/skapp/community/common/service/impl/JwtServiceImpl.java
> main to develop

- src/main/java/com/skapp/community/common/service/impl/JwtServiceImpl.java
> main to dev

- src/main/java/com/skapp/community/common/service/impl/JwtServiceImpl.java
- src/main/java/com/skapp/community/common/service/impl/OrganizationServiceImpl.java
- src/main/java/com/skapp/community/common/type/OrganizationConfigType.java
- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveCycleServiceImpl.java
> feat(common): google calendar config for organisation

- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveEmailServiceImpl.java
- src/main/resources/community/templates/email/en/leave/leave-module-manager-approved-multi-day-leave.html
- src/main/resources/community/templates/email/en/leave/leave-module-manager-approved-single-day-leave.html
- src/main/resources/community/templates/email/en/leave/leave-module-manager-declined-multi-day-leave.html
- src/main/resources/community/templates/email/en/leave/leave-module-manager-declined-single-day-leave.html
- src/main/resources/community/templates/email/en/leave/leave-module-manager-revoked-multi-day-leave.html
- src/main/resources/community/templates/email/en/leave/leave-module-manager-revoked-single-day-leave.html
> fix(email): wrong leave email templates

- src/main/java/com/skapp/community/common/service/impl/AuthServiceImpl.java
- src/main/java/com/skapp/community/common/service/impl/JwtServiceImpl.java
- src/main/java/com/skapp/community/common/service/impl/OrganizationServiceImpl.java
- src/main/java/com/skapp/community/common/type/OrganizationConfigType.java
- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveCycleServiceImpl.java
- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveEmailServiceImpl.java
- src/main/resources/community/templates/email/en/leave/leave-module-manager-approved-multi-day-leave.html
- src/main/resources/community/templates/email/en/leave/leave-module-manager-approved-single-day-leave.html
- src/main/resources/community/templates/email/en/leave/leave-module-manager-declined-multi-day-leave.html
- src/main/resources/community/templates/email/en/leave/leave-module-manager-declined-single-day-leave.html
- src/main/resources/community/templates/email/en/leave/leave-module-manager-revoked-multi-day-leave.html
- src/main/resources/community/templates/email/en/leave/leave-module-manager-revoked-single-day-leave.html
> Release sprint 3

- src/main/java/com/skapp/community/common/payload/request/UpdateOrganizationRequestDto.java
- src/main/resources/community/db/changelog/db.changelog.yml
- src/main/resources/community/db/changelog/ddl-script/common-ddl-script-v1-edit-organization.sql
> fix: organization validation error

- src/main/java/com/skapp/community/common/controller/v1/OrganizationController.java
- src/main/java/com/skapp/community/common/service/impl/OrganizationServiceImpl.java
- src/test/resources/data.sql
…ion details, then it's getting changed as a mandatory field
- 
1.
> Fix: #172 - company website update with empty company website

- src/main/java/com/skapp/community/common/type/EmailBodyTemplates.java
- src/main/resources/community/templates/email/email-templates.yml
- src/main/resources/community/templates/email/en/esignature/esignature-module-document-signer-email.html
- src/main/resources/community/templates/email/en/esignature/esignature-module-document-viewer-email.html
…entation Added.
- EP - Esignature:  Email Templates for Envelope creation Added.
1.
> feat: 277 Send email to recipients Implementation Added. 

- src/main/java/com/skapp/community/peopleplanner/repository/impl/EmployeeTeamRepositoryImpl.java
> fix: clockin summary filter issue

- src/main/java/com/skapp/community/peopleplanner/repository/impl/EmployeeTeamRepositoryImpl.java
> fix: attendance dashboard summery issue in team filter

- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
> fix: issue in super admin updates his own profile

- src/main/java/com/skapp/community/peopleplanner/repository/EmployeeRoleDao.java
> fix: user role limitation termination issue

- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
> Release super admin update fix

- src/main/java/com/skapp/community/common/exception/GlobalExceptionHandler.java
- src/main/resources/application-non-prd.yml
> feat: #381 - Stripe subscription verify webhook and get subscription details api

- src/main/java/com/skapp/community/common/exception/GlobalExceptionHandler.java
- src/main/java/com/skapp/community/common/service/impl/AuthServiceImpl.java
> Feat - #381 - stripe payment methods related apis

- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
- src/main/resources/application-non-prd.yml
> Sprint 3 main pull

- pom.xml
- src/main/java/com/skapp/community/common/config/SecurityConfig.java
- src/main/java/com/skapp/community/common/constant/CommonMessageConstant.java
- src/main/java/com/skapp/community/common/util/DateTimeUtils.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
- src/main/resources/application-non-prd.yml
- src/main/resources/community/messages/common-messages.properties
> Feat: auth related impl changes

- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveAnalyticsServiceImpl.java
> fix/581: user termination issue in leave utilization

- src/main/java/com/skapp/community/common/repository/SystemVersionDao.java
- src/main/java/com/skapp/community/common/service/SystemVersionService.java
- src/main/java/com/skapp/community/common/service/impl/JwtServiceImpl.java
- src/main/java/com/skapp/community/common/service/impl/SystemVersionServiceImpl.java
> Fix: redis and stripe changes

- src/main/java/com/skapp/community/leaveplanner/payload/LeaveRequestFilterDto.java
- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveServiceImpl.java
> feat/302: added export leave requests

- src/main/java/com/skapp/community/timeplanner/service/impl/TimeAnalyticsServiceImpl.java
> feat: formatting and import fixes

- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveServiceImpl.java
> hotfix: leave request is export

- src/main/java/com/skapp/community/common/service/EmailService.java
- src/main/java/com/skapp/community/common/service/impl/EmailServiceImpl.java
- src/main/java/com/skapp/community/common/type/EmailBodyTemplates.java
- src/main/java/com/skapp/community/common/type/EmailMainTemplates.java
- src/main/java/com/skapp/community/common/type/EmailTemplates.java
> hotfix: email template missing in community

- src/main/java/com/skapp/community/timeplanner/service/impl/TimeServiceImpl.java
> fix: removed incrementing total allocated dates

- pom.xml
- src/main/java/com/skapp/community/common/service/impl/JwtServiceImpl.java
- src/main/java/com/skapp/community/common/util/CommonModuleUtils.java
- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveServiceImpl.java
- src/main/java/com/skapp/community/leaveplanner/util/LeaveModuleUtil.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
- src/main/java/com/skapp/community/peopleplanner/util/PeopleUtil.java
- src/main/java/com/skapp/community/timeplanner/service/impl/TimeAnalyticsServiceImpl.java
> feat: springboot version updates and sonarlint fixes

- src/main/java/com/skapp/community/peopleplanner/constant/PeopleMessageConstant.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
- src/main/resources/community/messages/people-messages.properties
> fix/820: free user limit issue

- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveEntitlementServiceImpl.java
> fix/440: zero entitlements are shown

- src/main/java/com/skapp/community/common/constant/CommonConstants.java
- src/main/java/com/skapp/community/common/service/OrganizationService.java
- src/main/java/com/skapp/community/common/service/impl/OrganizationServiceImpl.java
- src/main/java/com/skapp/community/common/util/CommonModuleUtils.java
- src/main/java/com/skapp/community/leaveplanner/repository/LeaveRequestRepository.java
- src/main/java/com/skapp/community/leaveplanner/repository/impl/LeaveRequestRepositoryImpl.java
- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveAnalyticsServiceImpl.java
- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveServiceImpl.java
- src/main/java/com/skapp/community/leaveplanner/util/LeaveModuleUtil.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/HolidayServiceImpl.java
- src/main/java/com/skapp/community/timeplanner/service/TimeService.java
- src/main/java/com/skapp/community/timeplanner/service/impl/TimeAnalyticsServiceImpl.java
- src/main/java/com/skapp/community/timeplanner/service/impl/TimeServiceImpl.java
> fix/463: time zone refactoring

- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveNotificationServiceImpl.java
- src/main/resources/community/templates/notification/notification-templates.json
> fix/624: nudge notification body not found

- src/main/java/com/skapp/community/common/constant/CommonConstants.java
- src/main/java/com/skapp/community/common/service/PushNotificationService.java
- src/main/java/com/skapp/community/common/service/impl/EmailServiceImpl.java
- src/main/java/com/skapp/community/common/service/impl/NotificationServiceImpl.java
- src/main/java/com/skapp/community/common/service/impl/PushNotificationServiceImpl.java
- src/main/resources/community/templates/notification/notification-templates.json
> fix/868: title undefined in push notification

- src/main/java/com/skapp/community/leaveplanner/payload/CustomLeaveEntitlementsFilterDto.java
- src/main/java/com/skapp/community/leaveplanner/repository/LeaveEntitlementRepository.java
- src/main/java/com/skapp/community/leaveplanner/repository/impl/LeaveEntitlementRepositoryImpl.java
- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveEntitlementServiceImpl.java
> fix/429: leave entitlement search not working

- src/main/java/com/skapp/community/common/constant/CommonMessageConstant.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
- src/main/resources/community/messages/common-messages.properties
> fix/940: user can delete himself

- src/main/java/com/skapp/community/leaveplanner/constant/LeaveModuleConstant.java
- src/main/java/com/skapp/community/leaveplanner/repository/impl/LeaveEntitlementRepositoryImpl.java
- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveEntitlementServiceImpl.java
> fix/443: max carry forward issue

- pom.xml
- src/main/java/com/skapp/community/common/repository/impl/DataResetRepositoryImpl.java
> feat: aurora db changes

- src/main/java/com/skapp/community/leaveplanner/repository/impl/LeaveRequestRepositoryImpl.java
- src/main/java/com/skapp/community/peopleplanner/repository/impl/EmployeeTeamRepositoryImpl.java
> fix/884: team filter not working in leave apply modal

- src/main/resources/community/templates/email/en/leave/leave-module-employee-approved-multi-day-leave.html
- src/main/resources/community/templates/email/en/leave/leave-module-employee-approved-single-day-leave.html
- src/main/resources/community/templates/email/en/leave/leave-module-manager-declined-single-day-leave.html
> fix: email template issues in leave

- src/main/java/com/skapp/community/common/service/impl/NotificationServiceImpl.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/JobServiceImpl.java
> fix/876: incorrect notification time

- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveEmailServiceImpl.java
- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveServiceImpl.java
- src/main/resources/community/templates/email/en/leave/leave-module-employee-auto-approved-multi-day-leave.html
- src/main/resources/community/templates/email/en/leave/leave-module-employee-auto-approved-single-day-leave.html
- src/main/resources/community/templates/notification/notification-templates.json
> fix: email and notification issues

- src/test/resources/application.yml
> fix: test failure after new db change

- src/main/java/com/skapp/community/peopleplanner/controller/v1/PeopleController.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
- src/test/java/com/skapp/community/peopleplanner/controller/v1/PeopleControllerIntegrationTest.java
> fix: #740 - bugfix people flow

- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveEmailServiceImpl.java
- src/main/java/com/skapp/community/timeplanner/service/impl/TimeEmailServiceImpl.java
- src/main/resources/community/templates/email/email-templates.yml
- src/main/resources/community/templates/email/en/leave/leave-module-manager-nudge-multi-day-leave.html
- src/main/resources/community/templates/email/en/leave/leave-module-manager-nudge-single-day-leave.html
- src/main/resources/community/templates/email/en/leave/leave-module-manager-revoked-multi-day-leave.html
> fix/998: email refactoring

- src/main/java/com/skapp/community/leaveplanner/repository/impl/CarryForwardInfoRepositoryImpl.java
- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveEntitlementServiceImpl.java
> fix/443: carry forward delete issue

- pom.xml
> feat: route53 removal

- src/test/java/com/skapp/community/peopleplanner/controller/v1/PeopleControllerIntegrationTest.java
> hotfix: unit test failure after people refactoring

- src/main/java/com/skapp/community/common/constant/CommonConstants.java
- src/main/java/com/skapp/community/common/constant/ValidationConstant.java
- src/main/java/com/skapp/community/common/service/impl/AuthServiceImpl.java
- src/main/java/com/skapp/community/peopleplanner/constant/PeopleMessageConstant.java
- src/main/java/com/skapp/community/peopleplanner/mapper/PeopleMapper.java
- src/main/java/com/skapp/community/peopleplanner/payload/request/employee/personal/EmployeeExtraInfoDto.java
- src/main/java/com/skapp/community/peopleplanner/payload/request/employee/personal/EmployeePersonalHealthAndOtherDetailsDto.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/EmployeeValidationServiceImpl.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
- src/main/resources/community/messages/people-messages.properties
> Feat #927 - special tenant validation

- src/main/java/com/skapp/community/common/util/CommonModuleUtils.java
- src/main/java/com/skapp/community/peopleplanner/payload/request/employee/employment/EmployeeEmploymentPreviousEmploymentDetailsDto.java
> pull: people refactoring

- src/main/java/com/skapp/community/peopleplanner/model/EmployeeRole.java
- src/main/java/com/skapp/community/peopleplanner/repository/EmployeeManagerDao.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/EmployeeValidationServiceImpl.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
> fix: timeline issues fixed

- src/main/java/com/skapp/community/common/service/impl/AuthServiceImpl.java
> fix: #1044 #1043 - Subscription Cancellation Fixes

- src/main/java/com/skapp/community/timeplanner/service/impl/AttendanceNotificationServiceImpl.java
> fix/623: notification for time request manager

- src/main/java/com/skapp/community/peopleplanner/mapper/PeopleMapper.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
> fix/1070,1073: nin and team issues

- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
> fix: visa details edit issue

- src/main/java/com/skapp/community/peopleplanner/payload/response/ManagerResponseDto.java
- src/main/java/com/skapp/community/peopleplanner/repository/EmployeeManagerDao.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
> fix/1096: employment details not updated

- src/main/java/com/skapp/community/peopleplanner/util/Validations.java
> fix/1119: add accented and diacritic letters to state and city

- src/main/java/com/skapp/community/timeplanner/service/impl/TimeServiceImpl.java
> fix/1134: can not approve or decline time request

- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
> fix/1159: previous employee details issue

- src/main/java/com/skapp/community/peopleplanner/payload/request/EmployeeBulkDto.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
> fix/1156: change bulk upload template

- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
> fix/1241: probation start end dates clear issue

- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleReadServiceImpl.java
> hotfix: nin issue

- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleReadServiceImpl.java
> fix/1236: people admin can not see supervisors

- pom.xml
- src/main/java/com/skapp/community/common/util/CommonModuleUtils.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/EmployeeValidationServiceImpl.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
> fix : #1288 people edit personal details issues

- src/main/java/com/skapp/community/common/config/SecurityConfig.java
> fix: formatting and import issues

- src/main/java/com/skapp/community/common/config/SecurityConfig.java
- src/main/java/com/skapp/community/leaveplanner/service/LeaveNotificationService.java
- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveEmailServiceImpl.java
- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveNotificationServiceImpl.java
- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveServiceImpl.java
- src/main/java/com/skapp/community/peopleplanner/service/RolesService.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/RolesServiceImpl.java
- src/main/java/com/skapp/community/peopleplanner/util/PeopleUtil.java
- src/main/java/com/skapp/community/timeplanner/service/impl/AttendanceNotificationServiceImpl.java
- src/main/java/com/skapp/community/timeplanner/service/impl/TimeEmailServiceImpl.java
> fix/780,1282: email notifications for non privileged managers

- src/main/java/com/skapp/community/peopleplanner/payload/response/EmployeeDirectoryResponseDto.java
- src/main/java/com/skapp/community/peopleplanner/service/v2/impl/PeopleServiceImplV2.java
> fix: api changes in get employees

- src/main/java/com/skapp/community/peopleplanner/constant/PeopleConstants.java
- src/main/java/com/skapp/community/peopleplanner/repository/EmployeePeriodDao.java
- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
- src/main/java/com/skapp/community/peopleplanner/type/EmployeePeriodSort.java
> fix/1510: employee period duplication handled

- src/main/java/com/skapp/community/common/component/ProfileActivator.java
> fix: admin dashboard emails prd

- src/main/java/com/skapp/community/leaveplanner/service/LeaveAnalyticsService.java
- src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveAnalyticsServiceImpl.java
- src/main/java/com/skapp/community/peopleplanner/repository/EmployeeRepository.java
- src/main/java/com/skapp/community/peopleplanner/repository/impl/EmployeeRepositoryImpl.java
> hotfix: #1539 - Managers cannot see the employee entitlements

- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
> fix: date of birth not saving

- src/main/java/com/skapp/community/peopleplanner/repository/impl/EmployeeRepositoryImpl.java
> feat: #1521 people directory esign roles filter

- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
> hotfix: date of birth not saving issue

- src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
> fix: null issue in email validation
